name: Capstone CI/CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build-test-scan-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build backend image
        run: docker build -t capstone-backend ./backend

      - name: Build frontend image
        run: docker build -t capstone-frontend ./frontend

      - name: Run backend container (basic test)
        run: |
          docker run -d -p 5000:5000 --name backend-test capstone-backend
          sleep 5
          docker ps
          docker stop backend-test

      - name: Docker images list
        run: docker images

