name: Capstone CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  build-test-scan-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build Backend Image
      run: docker build -t capstone-backend ./backend

    - name: Run Unit Tests
      run: docker run capstone-backend pytest

    - name: Scan Image with Trivy
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: capstone-backend

    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

    - name: Push Image
      run: |
        docker tag capstone-backend ${{ secrets.DOCKER_USERNAME }}/capstone-backend:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/capstone-backend:latest

    - name: Deploy to Staging
      run: bash scripts/deploy.sh
